domains:
  example.com:
    ssl:
      enabled: true
      forced: true
      email: my.example@emailadr.es
    subdomains:
      alpha: http://1.2.3.4:1234/
      beta: http://2.3.4.5:2345/
      gamma: http://3.4.5.6:3456/
      delta: http://4.5.6.7:4567/
    forward_others: https://github.com/itavero/revprox

dns:
  default:
    type: cloudflare
    config:
      CLOUDFLARE_EMAIL: your@email.address
      CLOUDFLARE_API_KEY: 123456abcdef